### ISSUE TITLE
Genesis returns 200 while the testnet deployment reports an error

### ISSUE THREAD

**Issue by atoulme** [Whiteblock/genesis#73]
**To Reproduce**
1. Deploy genesis
2. Run: ```curl -X POST http://localhost:8000/testnets/ -d '{
   "servers":[1],
   "blockchain":"blah",
   "nodes":4,
   "images":["plumtree"],
   "resources":[{
       "cpus":"",
       "memory":""
   }]
}'```

**Expected behavior**
A 500 status code error is returned along with an explanation.

**Actual behavior**
A 200 status code is returned along with a testnet id.
The error log reports the following:
`ERRO[0184] an error was reported                         build=8de9c2fa-75ed-464b-87e2-e5b4cda678cb error="no entry found for blockchain \"blah\"" file=/Users/lb/go/src/github.com/whiteblock/genesis/manager/manager.go line=94`

**Comment by n8wb** [comment]
In order to check for errors or the status of the build, you must poll `GET /status/build/{id}`. The reason for this is that otherwise, your http request would time out as you wouldn't get a response back for a large chunk of time. (While the testnet is building). In short, a 200 from `POST /testnets/` indicates that the build started successfully.

**Comment by n8wb** [comment]
Updated POST /testnets/ in the wiki to document this behavior.
