### ISSUE TITLE
Add a vagrant file to allow cross os support

### ISSUE THREAD

**Issue by n8wb** [whiteblock/genesis#76]
A vagrantfile should be provided to allow for the proper use of Genesis on Mac (#71).

**Comment by atoulme** [comment]
This Vagrantfile should be based on Ubuntu 18.04.
It should configure the VM so it is given its own IP (bridge mode).
It should automatically install Docker and genesis, and start genesis as a service.
It should configure the Ubuntu VM so that it contains a user with sudo rights without entering password.
It should configure genesis to use this user for ssh.
It should configure genesis to expose itself on 0.0.0.0.

End to end test of this functionality would consist of running vagrant up, and run a curl command to deploy a sample testnet.
